### ISSUE TITLE
Bundling failed

### ISSUE THREAD

**Issue by tushgup** [danakt/spell-checker.js#1]
Hey! Thank you for working on this. Tried using this package today, ran into two errors:

1. Shouldn't the import statement by 'const spell = require('spell-checker')' as compared to 'const spell = require('spell-checker-js')' mentioned in the documentation? - because the latter returns a haste-map error.

2. If I change that, I run into a syntax error: 
![image](https://user-images.githubusercontent.com/5716459/47265842-8a0a6280-d54b-11e8-86c0-c4cbb4f85c28.png)

**Comment by danakt** [comment]
@tushgup you have installed the wrong package (`spell-checker` instead of `spell-checker-js`). I think it was my fault that there was a mistake in the [Readme](https://github.com/danakt/spell-checker.js/blob/master/README.md). Try to install package via `npm install spell-checker-js`

**Comment by muditasisodia** [comment]
Hi, I installed spell-checker-js but I'm running into the same haste-map error as before

![image](https://user-images.githubusercontent.com/16901159/47266508-44eb2e00-d555-11e8-9861-7c233375c80c.png)

**Comment by tushgup** [comment]
@danakt yep, I'm getting the same error as @muditasisodia.

**Comment by danakt** [comment]
@tushgup @muditasisodia are you try to use the package in React Native, right?

**Comment by muditasisodia** [comment]
yes

**Comment by danakt** [comment]
@muditasisodia Unfortunately, I didn't consider support of React Native while development of this package. The node.js API is different from the React Native API. Maybe [rn-nodeify](https://github.com/tradle/rn-nodeify) will help you.

**Comment by tushgup** [comment]
oh! my bad. I recently used a different npm package which didn't specifically mention support for react-native, so I assumed that all of them would work.

My bad! Thanks for the quick response. Closing the issue. 👍
