### ISSUE TITLE
React JS integration ?

### ISSUE THREAD

**Issue by Tisoy21** [danakt/spell-checker.js#3]
hello i want to use this package but seems i got error on my end ? any help would appreciate

<img width="701" alt="Screen Shot 2020-04-10 at 9 42 10 PM" src="https://user-images.githubusercontent.com/44186119/78995097-355e0b80-7b74-11ea-9db4-6affdb287d0d.png">

<img width="701" alt="Screen Shot 2020-04-10 at 9 42 10 PM" src="https://user-images.githubusercontent.com/44186119/78995099-37c06580-7b74-11ea-81f1-fd40be812e47.png">

**Comment by danakt** [comment]
Unfortunately, this tool can only be used in node.js
